---
- name: Configure CentOS with Oracle Database 12c
  hosts: oradb
  become: true
  vars_files:
    # User defined variables for infrastructure
    - infra-vars.yml
    - db-vars.yml
    # User Passwords
    - secrets.yml
  roles:
    - role: linux-oracle
    - role: oracle-install
      become_user: '{{ oracle_user }}'
    - role: sqlplus-install